## Hands on!

In [4]:
import sys 
import numpy as np

### Basic Numpy Arrays

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
a = np.array([1,2,3,4])

In [7]:
b = np.array([0,.5,1,1.5,2])

In [8]:
a[0], a[1]

(1, 2)

In [9]:
a[0:]

array([1, 2, 3, 4])

In [10]:
a[1:3]

array([2, 3])

In [11]:
a[1:-1]

array([2, 3])

In [12]:
a[::2]

array([1, 3])

In [13]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0,2,-1]]

array([0., 1., 2.])

## Array Types

In [15]:
a

array([1, 2, 3, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b.dtype = int

In [19]:
np.array([1,2,3,4],dtype=np.float_)

array([1., 2., 3., 4.])

In [20]:
c = np.array(['a','b','c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a':1}, sys])

In [23]:
d.dtype

dtype('O')

## Dimensions and shapes

In [24]:
A = np.array([
    [1,2,3],
    [3,4,5]
])

In [25]:
A.shape

(2, 3)

In [26]:
A.ndim

2

In [27]:
A.size

6

In [28]:
B = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [29]:
B.shape

(2, 2, 3)

In [30]:
B.ndim

3

In [31]:
B.size

12

In [32]:
C = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

## Indexing and slicing of matrices

In [33]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [34]:
A[1]

array([4, 5, 6])

In [35]:
A[1][0]

4

In [36]:
A[1,0]

4

In [37]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [39]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [40]:
A[:2, 2:]

array([[3],
       [6]])

In [41]:
A[1] = np.array([10,10,10])

In [42]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [43]:
A[2] = 99

In [44]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary Statistics

In [45]:
a = np.array([1,2,3,4])

In [46]:
a.sum()

10

In [47]:
a.mean()

2.5

In [48]:
a.std()

1.118033988749895

In [49]:
a.var()

1.25

In [50]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [51]:
A.sum()

45

In [52]:
A.mean()

5.0

In [53]:
A.std()

2.581988897471611

In [54]:
A.var()

6.666666666666667

In [55]:
A.sum(axis=0)

array([12, 15, 18])

In [56]:
A.sum(axis=1)

array([ 6, 15, 24])

In [57]:
A.mean(axis=0)

array([4., 5., 6.])

In [58]:
A.mean(axis=1)

array([2., 5., 8.])

In [59]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [60]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [61]:
A.var(axis=0)

array([6., 6., 6.])

In [62]:
A.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

______________________

## Broadcasting and Vectorized Operations

In [66]:
a = np.arange(4)

In [67]:
a

array([0, 1, 2, 3])

In [68]:
a + 10

array([10, 11, 12, 13])

In [69]:
a * 10

array([ 0, 10, 20, 30])

In [70]:
a += 100

In [71]:
a

array([100, 101, 102, 103])

In [72]:
l = [0,1,2,3]

In [73]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [74]:
a = np.arange(4)

In [75]:
a

array([0, 1, 2, 3])

In [76]:
b = np.array([10,10,10,10])

In [77]:
a + b

array([10, 11, 12, 13])

In [78]:
a * b

array([ 0, 10, 20, 30])

_____________
## Boolean arrays

In [79]:
a = np.arange(4)

In [84]:
a

array([0, 1, 2, 3])

In [85]:
a[[0, -1]]

array([0, 3])

In [86]:
a[[True,False,False,True]]

array([0, 3])

In [87]:
a >= 2

array([False, False,  True,  True])

In [88]:
a[a>=2]

array([2, 3])

In [89]:
a.mean()

1.5

In [90]:
a[a > a.mean()]

array([2, 3])

In [91]:
a[~(a > a.mean())]

array([0, 1])

In [92]:
a[(a == 0) | (a ==1)]

array([0, 1])

In [93]:
a[(a <= 2) & (a % 2 ==0)]

array([0, 2])

In [114]:
A = np.random.randint(100, size=(3,3))

In [115]:
A

array([[95, 66, 35],
       [25, 91,  0],
       [44, 53, 76]])

In [116]:
A[np.array([
    [True,False,True],
    [False,True,False],
    [True,False,True]
])]

array([95, 35, 91, 44, 76])

In [117]:
A > 30

array([[ True,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [118]:
A[A > 30]

array([95, 66, 35, 91, 44, 53, 76])

## Linear Algebra

In [119]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [120]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [121]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [122]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [123]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [124]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

### Int, floats

In [126]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [127]:
# longs are even larger
sys.getsizeof(10**100)

72

In [128]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [129]:
np.dtype(float).itemsize

8

## Lists are even larger

In [130]:
# A one-element list
sys.getsizeof([1])

64

In [131]:
np.array([1]).nbytes

8

## And performance is also important 

In [152]:
l = list(range(1000))

In [153]:
a = np.arange(1000)

In [154]:
%time np.sum(a ** 200)

CPU times: user 0 ns, sys: 449 µs, total: 449 µs
Wall time: 358 µs


2569844138599845172

In [155]:
%time sum([x ** 200 for x in l])

CPU times: user 379 µs, sys: 363 µs, total: 742 µs
Wall time: 745 µs


4491780109828715398806956135004011115830667433971488115879324388794265549092407281235307402723453339470576218658751122865146922690853359129443652809996004868021845296841838197078155832679142847804505687252938516290452637180495534815821213029385838431420458947020935858283101128463968855523906985274509140238014869585384849637682638706668352114682778752425823086385695958139564250025741680536426920802883025926024978905836744082239500762423620928841516062449235592904058742182065810651661989711289652322135314726685802088481386568286471221076853619033328308247047879369072615450839838938546750281813300

## Useful numpy functions

__random__

In [174]:
np.random.random(size=2)

array([0.62096821, 0.51498311])

In [175]:
np.random.normal(size=2)

array([-1.24055391, -0.93373245])

In [176]:
np.random.rand(2,4)

array([[0.01190027, 0.06133714, 0.2874032 , 0.34425239],
       [0.03988042, 0.06231749, 0.78529926, 0.9537369 ]])

__arange__

In [177]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [179]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

__reshape__

In [180]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [181]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

__linspace__

In [182]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [183]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [184]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

__zeros, ones, empty__

In [185]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [186]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [187]:
np.zeros((3,3), dtype=np.int_)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [188]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [189]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [190]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [191]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

__identity and eye__

In [192]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [193]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [194]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [195]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [196]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [197]:
"Hello World"[6]

'W'